export default {
    footer: '.gg-footer',
    footerCont: '.gg-footer-cont',
    footerLine: '.gg-footer-line',
    footerInfo: '.gg-footer-info',
    footerInfoGrp: '.gg-footer-cc-text span',
    footerFooter: '.gg-footer-cc',
    footerLogo: '.gg-footer-cc-img',
    //footerFooterLink: 'gg-footer-link-a',
    footerAllumaOrg: '',
    footerAboutline1: '.gg-footer-hdr1',
    footerFooterline2: '.gg-footer-hdr2',
    footerFooterline3: '.gg-footer-hdr3',
    footerFooterline4: '.gg-footer-hdr4',
    logo: '#logo',
    logoAllumaFasebook: '._6tay',
    logoAllumaTwitterUrl: 'https://twitter.com/WeAreAlluma',
    logoAllumaLinkedin: '',
    iconFasebook: '.gg-link-icon1',
    iconTwitter: '.gg-link-icon2',
    iconLinkedin: '.gg-link-icon3',
    footerLink: '.gg-footer-link gg-footer-link1',
}