export default {
    loginMain: '.gg-login-main',
    loginBackground: '.gg-login-bg',
    loginForm: '.gg-login-form',
    loginFormTitle1: '.gg-login-form-title1:nth-child(1)',
    loginFormTitle2: '.gg-login-form-title2',
    loginFormTitle3: '.gg-login-form-title3:nth-child(3)',
    loginFormTitle4: '.gg-login-form-title1:nth-child(4)',
    loginLinkText: 'a:nth-child(1)', 
    loginBtnLogin: 'button.gg-btn',  
    loginErrorInputMessage: 'li:nth-child(1)',
    loginErrorMessagePassword: 'li:nth-child(2)',
    usernameInputBox: '#Username',
    passwordInputBox: '#Password',
    usernameLink: 'a.gg-link:nth-child(1)',
    passwordLink: 'a.gg-link:nth-child(2)',
    loginInputBoxIcon: '.gg-form-input-icon',
    Img: 'div:nth-child(1) svg',
    loginLableText: '.gg-label-text',
    titleText: 'body .gg-login-form-title2',   
}