export default {
    footerText: 'Copyright 2019',
    footerText1: 'Alluma',
    footerText2: 'Non-discrimination Policy',
    footerText3: 'Privacy Policy',
    footerText4: 'Terms of Use',
    footerLogoSrc: '/Allumalogo_v1.png' ,
    footerLogoWidth: '232px',
    footerlogoAlign: 'middle',
    footerLinkRedirect: 'https://www.alluma.org/',
    footerBgColor: 'rgba(0,0,0,0)',
    footerFontSize: '14px',
    footerInfoGrpTextSize: '15px',
    footerInfGrpTextColor: 'rgba(84,84,92,1)',
    footerAllumaToTwitter: 'https://twitter.com/WeAreAlluma',
}